### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by ExoticWifi** [ExoticWifi/CourseKeep-Android#1]
### This is the list of features I need to add to the app

- Course List View
- [ ]  swipe right to left on the cell to give remove option
- [ ]  show app version number in settings screen

- Add Course View
- [ ] add validation

- Course Detail View
- [ ] add teacher is a dropdown
- [ ] swipe on teacher to reveal delete option
- [ ] holding on teacher will reveal share option
